# application.properties
# Profil par défaut


mailjet.api.key=45bfe433bc0e20daea6e5ffca05b2ed5
mailjet.api.secret=b9604392619117d3c14f166dd3461a38 

#spring.profiles.active=dev
spring.profiles.active=prod

spring.application.name=SecurityLearning

# PORT POUR RENDER (IMPORTANT)
server.port=${PORT:8080}



# Chargement des properties communes
spring.config.import=optional:file:.env[.properties]

# Désactiver la page d'erreur par défaut de Spring Boot
server.error.whitelabel.enabled=false