# application-prod.properties
server.port=${PORT:8080}

# Configuration Neon.tech
spring.datasource.url=${DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Upload fichiers
server.servlet.multipart.max-file-size=10MB
server.servlet.multipart.max-request-size=10MB

# Logging
logging.level.root=INFO
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.main=DEBUG

# H2 Console désactivée
spring.h2.console.enabled=false

# JWT
jwt.secret=${JWT_SECRET}
jwt.access-expiration=900000
jwt.refresh-expiration=604800000

# GitHub
github.token=${GITHUB_TOKEN}
github.username=${GITHUB_USERNAME}
github.repo=${GITHUB_REPO}