# application.properties
# Profil par défaut

#spring.profiles.active=dev
spring.profiles.active=prod

spring.application.name=SecurityLearning

# PORT POUR RENDER (IMPORTANT)
server.port=${PORT:8080}



# Chargement des properties communes
spring.config.import=optional:file:.env[.properties]

# Désactiver la page d'erreur par défaut de Spring Boot
server.error.whitelabel.enabled=false